import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/app/nav/Navbar";

import { config } from "@fortawesome/fontawesome-svg-core";
import "@fortawesome/fontawesome-svg-core/styles.css";
import React from "react";

config.autoAddCss = false;

export const metadata: Metadata = {
  title: "Carsties",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Navbar />
        <main className={`container mx-auto px-5 pt-10`}>{children}</main>
      </body>
    </html>
  );
}
